
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: scheme-service
          uri: lb://scheme-service
          predicates:
            - Path=/api/schemes/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
        - id: discovery-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**



logging:
  level:
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: INFO

          gateway=TRACE:

server:
  port: 8080


