server:
  port: 0


spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3307/msademo
    password: Ur@$2022
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  application:
    name: user-service

# Resilience4j properties
resilience4j:
  circuitbreaker:
    instances:
      schemeservice:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        sliding-window-type: count_based
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true