server:
  port: 8080


spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3307/msademo
    password: Ur@$2022
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  application:
    name: user-service